### ISSUE TITLE
Click on any screen element prevented in demo.

### ISSUE THREAD

**Issue by gaelmotte** [gao-sun/react-screen#1]
Hi,

In demo available at https://gao-sun.github.io/react-screen/, it feels like default behavior is to stack all screens and make them transparent.
Probleme with this technique is it is not possible to get click events on currently shown screen, or simply inspecting element in screen. Each time, the last screen gets click events.

Playing with Z indexes should do it, but even though there are values set of 99998, i cannot get why the current screen doesn't get it's z index value changed.

**Comment by gaelmotte** [comment]
considered fix : 
 in animation keyframe at in and out of screen, change z-index accordingly

**Comment by gao-sun** [comment]
Hi! Thank you so much for your feedback. I'm in trip these days and I'll fix it asap when I come back.

**Comment by gaelmotte** [comment]
Hey !

Thanks for fixing the two issues ! :) I shall try asap the new behaviors you implemented :)
You may want to update your github pages to reflect theses changes.

By the way, the react-screen.js file from your github pages is 243Kb, compared to the 6Kb of your dist.
What is the difference ?

**Comment by gao-sun** [comment]
Hi,

Sorry I didn't check my personal email and my Github notification these days, sorry about delayed response. I've updated my Github page to the new version. For the size part, because in the Github page it contains whole React code and other running essentials, in dist it just contains react-screen itself.

**Comment by gaelmotte** [comment]
Hi again ! 
No problem for the delays ! 
Thanks for the explanations, the update, and the component of course ! 
Works fine now ! 
Cheers !

**Comment by gao-sun** [comment]
Thank you for support. I fixed notification issue on my cellphone and now I can respond timely. Cheers!
